// Generated by gencpp from file simple_laserscan/Spying.msg
// DO NOT EDIT!


#ifndef SIMPLE_LASERSCAN_MESSAGE_SPYING_H
#define SIMPLE_LASERSCAN_MESSAGE_SPYING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simple_laserscan
{
template <class ContainerAllocator>
struct Spying_
{
  typedef Spying_<ContainerAllocator> Type;

  Spying_()
    : distance(0.0)
    , direction(0.0)  {
    }
  Spying_(const ContainerAllocator& _alloc)
    : distance(0.0)
    , direction(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;

   typedef float _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::simple_laserscan::Spying_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_laserscan::Spying_<ContainerAllocator> const> ConstPtr;

}; // struct Spying_

typedef ::simple_laserscan::Spying_<std::allocator<void> > Spying;

typedef boost::shared_ptr< ::simple_laserscan::Spying > SpyingPtr;
typedef boost::shared_ptr< ::simple_laserscan::Spying const> SpyingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_laserscan::Spying_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_laserscan::Spying_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simple_laserscan::Spying_<ContainerAllocator1> & lhs, const ::simple_laserscan::Spying_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance &&
    lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simple_laserscan::Spying_<ContainerAllocator1> & lhs, const ::simple_laserscan::Spying_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simple_laserscan

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::simple_laserscan::Spying_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_laserscan::Spying_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_laserscan::Spying_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_laserscan::Spying_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_laserscan::Spying_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_laserscan::Spying_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_laserscan::Spying_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2ac8ba2b8d9e9c7149b80102e904708";
  }

  static const char* value(const ::simple_laserscan::Spying_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2ac8ba2b8d9e9c7ULL;
  static const uint64_t static_value2 = 0x149b80102e904708ULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_laserscan::Spying_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_laserscan/Spying";
  }

  static const char* value(const ::simple_laserscan::Spying_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_laserscan::Spying_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 distance\n"
"float32 direction\n"
;
  }

  static const char* value(const ::simple_laserscan::Spying_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_laserscan::Spying_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Spying_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_laserscan::Spying_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_laserscan::Spying_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "direction: ";
    Printer<float>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_LASERSCAN_MESSAGE_SPYING_H
